language: python

matrix:
  include:
    - sudo: false
      dist: trusty
      env: INSTALL=no TESTFILE=./wftests/warrior_tests/projects/pj_common_actions.xml
      python: 2.7
    - sudo: false
      dist: trusty
      env: INSTALL=yes TESTFILE=./wftests/ci/pylint.sh PYLINT=yes
      python: 2.7
    - sudo: false
      dist: trusty
      env: INSTALL=yes TESTFILES=yes
      python: 2.7
    - sudo: required
      dist: trusty
      env: INSTALL=yes TESTFILE=./wftests/warrior_tests/testcases/selenium_tests/tc_selenium_headless.xml SELENIUM=yes
      python: 2.7
      addons:
        firefox: "46.0"
        chrome: stable
    - sudo: false
      dist: trusty
      env: INSTALL=no TESTFILE=./wftests/warrior_tests/testcases/framework_tests/cond_var/pass.xml COPILOT=yes
      python: 2.7

install:
  - if [[ ${COPILOT} = "yes" ]]; then
      python setup.py install ;
    fi
  - if [[ ${INSTALL} = "yes" ]] && [[ ! -z ${TRAVIS_PULL_REQUEST_BRANCH} ]]; then
      pip install pexpect==4.2 ;
      pip install requests==2.9.1 ;
      pip install selenium==2.53.0 ;
      pip install lxml==3.3.3 ;
      pip install paramiko==1.16.0 ;
      pip install pysnmp==4.3.2 ;
    fi
  - if [[ ${SELENIUM} = "yes" ]] && [[ ! -z ${TRAVIS_PULL_REQUEST_BRANCH} ]]; then
      pip install pyvirtualdisplay==0.2.1 ;
      wget https://chromedriver.storage.googleapis.com/2.36/chromedriver_linux64.zip;
      unzip chromedriver_linux64.zip;
      chmod +x chromedriver;
      mv chromedriver ~/bin/chromedriver;
    fi

script:
  - if [[ ${PYLINT} = "yes" ]]; then
      $TESTFILE ;
    elif [[ -z ${TRAVIS_PULL_REQUEST_BRANCH} ]]; then
      python ./warrior/Warrior ./wftests/warrior_tests/testcases/framework_tests/cond_var/pass.xml ;
    elif [[ ${TESTFILES} = "yes" ]]; then
      python ./warrior/Warrior ./wftests/warrior_tests/projects/pj_*.xml ;
    elif [[ ${SELENIUM} = "yes" ]]; then
      python ./warrior/Warrior $TESTFILE ;
      pip install selenium==3.8 ;
      python ./warrior/Warrior $TESTFILE ;
    else
      python ./warrior/Warrior $TESTFILE ;
    fi

after_success:
  - if [[ ${COPILOT} = "yes" ]] && [[ -z ${TRAVIS_PULL_REQUEST_BRANCH} ]]; then
      bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
    fi
