language: python

matrix:
  include:
    - sudo: false
      dist: trusty
      env: INSTALL=no TESTFILE=./wftests/warrior_tests/projects/pj_common_actions.xml
      python: 2.7
    - sudo: required
      dist: trusty
      env: INSTALL=no TESTFILE=./wftests/warrior_tests/projects/pj_common_actions.xml
      python: 2.7

install:
  - echo "hm" ;

script:
    - if [[ ${TRAVIS_PULL_REQUEST_BRANCH} = "" ]]; then
        echo "Yes" ;
      else
        echo ${TRAVIS_PULL_REQUEST_BRANCH} ;
      fi
