language: python

matrix:
  include:
    - sudo: false
      dist: trusty
      python: 2.7

script:
    - if [[ ${TRAVIS_PULL_REQUEST_BRANCH} = "" ]]; then
        echo "Yes" ;
      else
        echo ${TRAVIS_PULL_REQUEST_BRANCH} ;
      fi
